### PR TITLE
My notes for three meetups

### PR DESCRIPTION
**Pull request by jefftrull**
Hi Mike! Sorry I've been so slow about this.

I added an "images" directory with the idea that we might want to separate things that way. LMK what you think.

### CODE REVIEW

**Comment by wrightmikea** [comment]
Also, I have more notes I from several meetups, so when I get a chance, I will add more files (or add to yours)
I'd be happy to clean up your .org files to be more vanilla (and/or add relevant links to external web-sites).  If you want to demonstrate specific org-mode extensions, we could do those in separate .org files, with more info about the setup required.  Not every member of the meetup who is interested in org-mode will necessarily have LaTeX installed.

**Comment by jefftrull** [comment]
Ah, yes, I see! I didn't do a good job of scrubbing these. I will go back and make them plainer. Thanks for pointing that out.

**Comment by wrightmikea** [comment]
FYI, after installing the etoolbox and texlive-fonts-extra debian packages, I was able to use your org file to generate a PDF.  When viewing in emacs, zooming in show aliasing/fuzziness, but when using xpdf, zooming looks fine.
I'll play with MacTeX later.

**Comment by jefftrull** [comment]
It looks like the :B_frame: thing is a "tag" that's supposed to be ignored? beamer treats it as metadata, but it looks like the HTML exporter takes it literally... Unsure why.

**Comment by jefftrull** [comment]
OK the "tag" is there but so is a "property" that indicates the same thing (the specific headline should be treated as a Beamer frame) and it looks like I can safely removed the tag. Updated. I will look at the package requirements next.

**Comment by jefftrull** [comment]
So I tried uninstalling etoolbox (via its package `texlive-latex-extra`) and I find that even simple org files cannot be output as PDF... I removed all my beamer-specific stuff as well, I think. It seems that the use of LaTeX at all requires it. Without etoolbox are you able to produce pdfs?

**Comment by wrightmikea** [comment]
I don't think that I tried to produce a PDF from an org file on my recently installed Debian 9 system (before I installed etoolbox).  I sometimes publish to HTML.
I recall having to install several Debian packages in order to get org-mind-map-write to produce a PDF (but etoolbox wasn't one of them).

**Comment by jefftrull** [comment]
OK! Well, I suspect etoolbox is just a requirement for pdf generation. I've cleaned up the files a bit and HTML looks good to me - what do you think now?

**Comment by jefftrull** [comment]
Definitely not required :) TBH I just took my slides and changed their names. I'll take them out.

**Comment by jefftrull** [comment]
OK I did that and also moved export metadata into its own hidden section as described [here](https://stackoverflow.com/questions/7318051/org-mode-hide-buffer-settings-export-options)

**Pull request merged**
