### PR TITLE
Introduce my personal notes for 1/27/2021

### PR DESCRIPTION
**Pull request by jefftrull**
I grabbed a few notes from this meetup and thought it would be better if I supplied them as a PR. I'm sure you'll want to add a lot to it, as it's nowhere near complete.

I also kept the chat log, if that's of interest.

### CODE REVIEW

**Comment by agzam** [comment]
I think these can also be in the wiki, just like how we have the "Upcoming events" page; maybe we should create "Past events" and keep them updated. That way we'd have minimal overhead. e.g., Jeff can add a link to the meetup (sometimes people chat there, even though I'm not too fond of meetup.com); whoever has the recording uploaded to Youtube (or some other place) can add the link to the video; someone would post the notes, and later we can edit them. What do you guys think?

**Comment by jefftrull** [comment]
I'll leave that to @wrightmikea , who created the current structure. I would point out that we'll have to go back and update meetup.com, as I usually posted a link to the notes once I uploaded them.

**Comment by wrightmikea** [comment]
I will refactor these notes into the file at the new location: meetups/2021/20210127.org

**Comment by jefftrull** [comment]
If you'll let me know when the notes are all moved, I will update the links in Meetup.

**Comment by wrightmikea** [comment]
Hi Jeff,

   Thanks; that's on my todo list, so if you could do that it would be
great.  I pushed and merged all the 2021 meeting notes and future meeting
placeholders today.   I wanted to wait until we all agree on the next
meeting time/day before "announcing" (and rescheduling) the April meetup.
BTW, meetup.com whitelisted our new conference URL, yay!

    I also updated the README links.  I created a private repo for tracking
subtitle edits. I still need to update the wiki and the blog.   I still
need to update the meeting-notes index.org files for prior years.

   FYI, I uploaded the 8 videos to my youtube account where I'm working on
editing the subtitles.  The videos are not public, but reachable via
links.  I "published" these links in the 3/5 meeting notes.  Once I get the
subtitles finalized, then I will try to upload to the Emacs SF youtube --
haven't figured out how to do that yet (like, how do I switch to that
channel to see its dashboard?).  I have several links (e.g. to topics
mentioned and example gists) for the videos, which I plan to add to the
final videos.

   I'm also working on a couple of possible lightning talks, using the
latex title page from the videos to create a presentation, but my tex
installation on Arch Linux seems to be broken, so I'm reinstalling tex.
Hopefully others will have lightning talks (Howard tried to demo his hydras
last time and maybe he can try again).

    Also, I'm studying Sacha's gist org file to understand how to automate
our video post-production workflows.  I've read two ffmpeg books and found
some interesting recipes to try with future recordings.  I've decided to
focus more on ffmpeg scripts than spend too much time with flowblade,
kdenlive, or openshot (which I have successfully installed and used a bit).

     Looking forward to your talk tomorrow.

Mike

**Pull request closed without merging**
